<?php

  /**
   * @file
   * Core functionality for the EAIC
   *
   */

require_once __DIR__ . '/includes/islandora_solr.inc';
require_once __DIR__ . '/includes/islandora_solr_facet_pages.inc';
require_once __DIR__ . '/includes/blocks.inc';

/**
 * Implements hook_theme().
 */
function dss_eastasia_theme() {

  // Set path.
  /*
  $base = array(
		'path' => drupal_get_path('module', 'dss_eastasia') . '/theme',
		'file' => 'islandora_solr_facet_pages.theme.inc',
		);
  */

  return array(
	       'dss_eastasia_front_page' => array(
						  'arguments' => array('object' => NULL),
						  'file' => 'theme/theme.inc',
						  'template' => 'theme/islandora-page',
						  ),
	       'dss_eastasia_last_page' => array(
						 'arguments' => array('object' => NULL),
						 'file' => 'theme/theme.inc',
						 'template' => 'theme/islandora-page',
						 ),

	       'dss_eastasia_postcard' => array(
						'arguments' => array('object' => NULL),
						'file' => 'theme/theme.inc',
						'template' => 'theme/islandora-eastasia-postcard',
						),
	       // Default object template.
	       /*
	       'islandora_default' => array(
					    'file' => 'theme/theme.inc',
					    'template' => 'theme/islandora-object',
					    'variables' => array('islandora_object' => NULL),
					    ),
	       */
	       );
}

function dss_eastasia_theme_registry_alter(&$theme_registry) {

  /*
    'islandora_solr_facet_pages_letterer' => $base + array(
      'variables' => array(
        'facet_queries' => array(),
        'fq_map' => array(),
        'prefix' => NULL,
        'path' => NULL,
      ),
   */

  $theme_registry['islandora_book_book']['template'] = drupal_get_path('module', 'dss_eastasia') . '/theme/islandora-page';

  //$theme_registry['islandora_solr_facet_pages_letterer']['path'] = drupal_get_path('module', 'dss_eastasia') . '/theme';
  //$theme_registry['islandora_solr_facet_pages_letterer']['file'] = 'includes/theme.inc';
  $theme_registry['islandora_solr_facet_pages_letterer']['path'] = drupal_get_path('module', 'dss_eastasia') . '/includes';
  $theme_registry['islandora_solr_facet_pages_letterer']['file'] = 'islandora_solr_facet_pages.inc';

  $theme_registry['islandora_solr_facet_pages_results']['path'] = drupal_get_path('module', 'dss_eastasia') . '/theme';
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 *
 */
function dss_eastasia_islandora_bookcmodel_islandora_view_object($object) {

  $parent_pid = array_pop($object->getParents());

  if(preg_match('/^eastAsia\:/', $parent_pid)) {

    return theme('dss_eastasia_postcard', array('object' => $object));
  }
}

/**
 * Renders the Pages local menu task.
 *
 * @param FedoraObject $object
 *   The book object to fetch the pages from.
 *
 * @return string
 *   The HTML repersentation of the given books pages.
 */
function dss_eastasia_last_page_menu(FedoraObject $object) {

  return theme('dss_eastasia_last_page', array('object' => $object));
}

/**
 * Renders the Pages local menu task.
 *
 * @param FedoraObject $object
 *   The book object to fetch the pages from.
 *
 * @return string
 *   The HTML repersentation of the given books pages.
 */
function dss_eastasia_front_page_menu(FedoraObject $object) {

  return theme('dss_eastasia_front_page', array('object' => $object));
}

function dss_eastasia_islandora_book_book_menu(FedoraObject $object) {

  return theme('dss_eastasia_front_page', array('object' => $object));
}

/**
 * Determine whether or not to show this modules pages tab.
 *
 * @param FedoraObject $object
 *   The book object.
 *
 * @return bool
 *   TRUE if it should be shown, and FALSE if it should not be shown.
 */
function dss_eastasia_last_page_access_callback($object=NULL) {

  if(!isset($object)) {

    return FALSE;
  }

  $is_book = in_array('islandora:bookCModel', $object->models);

  // This should be avoided by checking for the namespaces within the Object
  $map = function($obj_pid) {

    return preg_match('/eastAsia/', $obj_pid);
  };

  $reduce = function($u, $v) {

    return $u || $v;
  };

  module_load_include('inc', 'islandora_paged_content', 'includes/utilities');

  // Grant access if this is a book, has more than one page, belongs to the EAIC collection
  //return islandora_object_access_callback(FEDORA_VIEW_OBJECTS, $object) && $is_book && sizeof(islandora_paged_content_get_pages($object)) > 1 && array_reduce(array_map($map, $object->getParents()), $reduce);
  return islandora_object_access_callback(FEDORA_VIEW_OBJECTS, $object) && $is_book && sizeof(islandora_paged_content_get_pages($object)) > 1 && array_reduce(array_map($map, $object->getParents()), $reduce);
}

function dss_eastasia_front_page_access_callback($object=NULL) {

  return TRUE;
}

/**
 * Access callback for "pages" menu
 *
 * @param FedoraObject $object
 *   The book object.
 *
 * @return bool
 *   TRUE if it should be shown, and FALSE if it should not be shown.
 *
 * @see islandora_book_pages_access_callback()
 *
 */
function dss_eastasia_pages_access_callback($object = NULL) {

  $parent_pid = array_pop($object->getParents());

  return !preg_match('/^eastAsia\:/', $parent_pid) && islandora_book_pages_access_callback($object);
}

/**
 * Implements hook_menu_alter().
 */
function dss_eastasia_menu_alter(&$items) {

  drupal_load('module', 'islandora_book');

  $items['islandora/object/%islandora_object/back'] = array(
							    'title' => 'Back',
							    'type' => MENU_LOCAL_TASK,
							    'page callback' => 'dss_eastasia_last_page_menu',
							    'page arguments' => array(2),
							    'access callback' => 'dss_eastasia_last_page_access_callback',
							    'access arguments' => array(2),
							    );

  /*
  $items['islandora/object/%islandora_object/front'] = array(
							     'title' => 'Front',
							     'type' => MENU_DEFAULT_LOCAL_TASK,
							     //'type' => MENU_LOCAL_TASK,
							     'page callback' => 'dss_eastasia_front_page_menu',
							     'page arguments' => array(2),
							     'access callback' => 'dss_eastasia_front_page_access_callback',
							     'access arguments' => array(2),
							     );
  */

  /*
  $items['islandora/object/%islandora_object/view']['title'] = 'Front';
  $items['islandora/object/%islandora_object/view']['page callback'] = 'dss_eastasia_islandora_book_book_menu';
  $items['islandora/object/%islandora_object/view']['page arguments'] = array(2);
  $items['islandora/object/%islandora_object/view/default']['title'] = 'Front';
  $items['islandora/object/%islandora_object/view/default']['page callback'] = 'dss_eastasia_islandora_book_book_menu';
  $items['islandora/object/%islandora_object/view/default']['page arguments'] = array(2);
  */

  // Ensure that East Asia Image Collections items do not have a "pages" menu item
  $items['islandora/object/%islandora_object/pages']['access callback'] = 'dss_eastasia_pages_access_callback';

  //unset($items['islandora/object/%islandora_object/view/default']);

  $items['browse']['page callback'] = 'dss_eastasia_islandora_solr_facet_pages_callback';
  $items['islandora/search']['page callback'] = '_dss_eastasia_islandora_solr';
}

  /*

  $items['islandora/object/%islandora_object/view/default']['title'] = 'Front';
  */

  /*
  $items['islandora/object/%islandora_object/view']['type'] = MENU_LOCAL_TASK;
  $items['islandora/object/%islandora_object/view/default']['type'] = MENU_LOCAL_TASK;
  */

  /*
  $items['islandora/object/%islandora_object/view'] = array(
							    'title' => 'Front',
							    'type' => MENU_DEFAULT_LOCAL_TASK,
							    'weight' => -1,
							    'page callback' => 'dss_eastasia_front_page_menu',
							    'page arguments' => array(2),
							    'access callback' => 'dss_eastasia_book_pages_access_callback',
							    'access arguments' => array(2),
							    );
  */
  /*
  $items['islandora/object/%islandora_object/view/default'] = array(
								    'title' => 'Front',
								    'type' => MENU_DEFAULT_LOCAL_TASK,
								    'weight' => -1,
								    'page callback' => 'dss_eastasia_front_page_menu',
								    'page arguments' => array(2),
								    'access callback' => 'dss_eastasia_book_pages_access_callback',
								    'access arguments' => array(2),
								    );
  */

  /*
  $items['islandora/object/%islandora_object/view'] = array(
    'title' => 'View',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -1,
  );
  $items['islandora/object/%islandora_object/view/default'] = array(
    'title' => 'View',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -1,
  );
   */

  /*
function islandora_solr_facet_pages_menu() {
  $items = array();

  // @TODO: create separate permission?
  $items['browse'] = array(
    'page callback' => 'islandora_solr_facet_pages_callback',
    'page arguments' => array(1, 2),
    'access callback' => 'islandora_solr_facet_pages_access_callback',
    'access arguments' => array(1),
    'type' => MENU_CALLBACK,
  );
*/

  /*
  $items['islandora/search'] = array(
    'title' => 'Search results',
    'page callback' => 'islandora_solr',
    'access arguments' => array('search islandora solr'),
    'type' => MENU_CALLBACK,
  );

   */
